mbes_ism:
  ros__parameters:
    stonefish: true
    laserscan_topic: /alpha_rise/stonefish/multibeam/data
    pointcloud_topic: "/alpha_rise/surveyor/pointcloud"
    pointcloud_pub_topic: "/alpha_rise/mbes/pointcloud/probability"
    range_resolution: 1.0